### ISSUE TITLE
Exit status 17: backend: no such file or directory

### ISSUE THREAD

**Issue by nileshtrivedi** [dockersamples/compose-dev-env#5]
While trying to load [this commit](https://github.com/dockersamples/compose-dev-env/commit/41b68fca917cf55bfaa0ccc9fdf126a410514be8) as a Dev Environment with Docker Desktop 4.2.0 (70708) on Mac OS 11.6, I get this non-intermittent failure:

```
Detecting main repo language...
Detected 'Go' as the main repository language.
could not find /var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-charming_wright/proxy/var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-charming_wright/proxy: stat /var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-charming_wright/proxy/var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-charming_wright/proxy: no such file or directory
exit status 17
```
This is reproducible even with clicking the link under "Try running a sample" on the dashboard:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/19304/141760577-608b32c2-be36-4ce1-a446-5d990ee310aa.png">

Although, this time it complained about a different folder missing:

```
Detected 'Go' as the main repository language.
could not find /var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-pensive_wozniak/backend/var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-pensive_wozniak/backend: stat /var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-pensive_wozniak/backend/var/folders/1f/wfpcf_k14gx_kx8sxsw3473m0000gn/T/volume-compose-dev-env-pensive_wozniak/backend: no such file or directory
exit status 17
```

**Comment by glours** [comment]
Hello @nileshtrivedi 

Compose `v1` and `v2` behave differently , I'll try to figure out what should be the right behaviour and propose a PR to fix that.
By the way the issue isn't in this sample, and you can fix this, for the moment, by turning off the use of Compose V2 in Docker Desktop

![compose-v2](https://user-images.githubusercontent.com/705411/141769409-a01d7c02-d322-4d17-ae5f-fe0e8993de01.png)

**Comment by glours** [comment]
A fix has been merged this morning, the sample should run fine with Compose V2 in the next release of Docker Desktop (maybe `4.3.0`)

**Comment by ranmocy** [comment]
Still see the same issue with Docker Desktop v4.3.0(71786) and Docker Compose v2.2.1.
Tested both "Use Docker Compose V2" checked and unchecked. Same error message:

```
Preparing to clone inside a volume
Installing credential helpers... done
Cloning into '/code'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.remote: Counting objects:  47% (30/63)remote: Counting objects:  17% (11/63)remote: Counting objects:  11% (7/63)
remote: Compressing objects: 100% (49/49), done.remote: Compressing objects:  83% (41/49)
remote: Total 63 (delta 19), reused 40 (delta 10), pack-reused 0
Receiving objects: 100% (63/63), 15.62 KiB | 533.00 KiB/s, done.Receiving objects:  87% (55/63)Receiving objects:  50% (32/63)Receiving objects:  33% (21/63)
Resolving deltas: 100% (19/19), done.
Detecting main repo language...
Detected 'Go' as the main repository language.
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/folders/g9/96m0c6rx2297y5f13b8kbg9m009nff/T/volume-compose-dev-env-peaceful_chatelet
```

**Comment by GoshaFighten** [comment]
Still getting this error on Ubuntu 22.04:

```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/volume-compose-dev-env-clever_ishizaka
```

![Screenshot_20220517_175336](https://user-images.githubusercontent.com/10522139/168841919-b1647be9-a3b0-4feb-8426-78c1d9351aa1.png)

The _Enable Docker Compose V1/V2 compatibility mode_ option is enabled:

![Screenshot_20220517_180234-1](https://user-images.githubusercontent.com/10522139/168844913-85342cb8-84f6-41f3-bcf3-a36db5d9a93b.png)

Docker Desktop version is 4.8.1 (78998):

![Screenshot_20220517_181049](https://user-images.githubusercontent.com/10522139/168845612-8eca016a-d1cd-48f3-9524-e2117afa11f9.png)

**Comment by zzhouj** [comment]
Add "/tmp" folder to Settings/Resources/File sharing, if you meet problem like me: "Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/volume-compose-dev-env-romantic_brown"
